-- Royal Square Financial: seed data.
--
-- Intentionally contains NO demo clients, policies, claims or requests.
--
-- The previous seed inserted fixed profile rows that reference auth.users(id), so it could never run
-- against a real project (and it would have fabricated clients in production). Real data now enters
-- the system like this:
--   * clients register in the client app (a profile + client file are created automatically, see 022)
--   * advisers capture their balance sheet, policies and investments in the adviser dashboard
--   * the provider catalogue is created by migration 016 and maintained in the dashboard
--
-- To create your first administrator see docs/database.md ("First admin").
